/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3Zqger0jaET
 */
'use client'
import { Button } from "@/components/ui/button"

import React, { useState } from 'react';
import { ResponsiveLine } from "@nivo/line";

function TextIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 6.1H3" />
      <path d="M21 12.1H3" />
      <path d="M15.1 18H3" />
    </svg>
  );
}

export function Homepage() {
  const [showOverlay, setShowOverlay] = useState(false);
  const [currentMessage, setCurrentMessage] = useState('');
  const [messageHistory, setMessageHistory] = useState([]);

  const toggleOverlay = () => {
    setShowOverlay(!showOverlay);
  };

  const sendMessage = async () => {
    if (!currentMessage.trim()) return;

    const userMessage = { sender: 'user', message: currentMessage };
    setMessageHistory([...messageHistory, userMessage]);

    // Update the fetch call to point to the Flask backend
    const response = await fetch('http://localhost:5000/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ userInput: currentMessage }), // Make sure the key matches what Flask expects
    });

    if (response.ok) {
      const { message } = await response.json(); // Assuming Flask returns { message: "response text" }
      const aiMessage = { sender: 'ai', message: message };
      setMessageHistory(prevHistory => [...prevHistory, aiMessage]);
    } else {
      console.error('Failed to fetch response');
    }

    setCurrentMessage('');
  };


  return (
    <>
      <header className="flex items-center justify-between w-full px-6 py-4 dark:bg-blue-900">
        <h1 className="text-3xl font-bold dark:text-white">IntellectQuest</h1>
        <div className="flex space-x-4">
          <button className="px-4 py-2 rounded-lg bg-blue-500 text-white dark:bg-blue-700 dark:text-white">
            Modules
          </button>
          <button className="px-4 py-2 rounded-lg bg-blue-500 text-white dark:bg-blue-700 dark:text-white">
            Quizzes
          </button>
          <button className="px-4 py-2 rounded-lg bg-blue-500 text-white dark:bg-blue-700 dark:text-white">
            Reports
          </button>
          <button className="px-4 py-2 rounded-lg bg-blue-500 text-white dark:bg-blue-700 dark:text-white">
            Login
          </button>
          <div className="avatar">
            <div className="w-10 rounded">
              <img src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg" />
            </div>
          </div>
        </div>
      </header>
      <div className="grid md:grid-cols-2 gap-4 items-start w-full px-6 py-6 dark:bg-blue-900">
        <div className="grid md:grid-cols-2 gap-4 items-start w-full max-w-7xl px-6 py-6 dark:bg-blue-900">
          <div className="space-y-6 dark:bg-blue-900">
            <div className="space-y-2">
              <h1 className="text-2xl font-bold dark:text-white">Modules</h1>
              <p className="text-sm leading-none text-gray-500 dark:text-gray-400">Explore available modules</p>
            </div>
            <div className="space-y-4">
              <div className="flex flex-col items-center space-y-4">
                <div className="flex items-center space-x-4">
                  <img
                    alt="Image"
                    className="rounded-lg"
                    height="64"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "64/64",
                      objectFit: "cover",
                    }}
                    width="64"
                  />
                  <div className="space-y-1.5">
                    <h2 className="text-lg font-semibold dark:text-white">Introduction to Computer Science</h2>
                    <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
                      An introduction to the foundational concepts in computer science.
                    </p>
                  </div>
                </div>
                <div className="w-full h-4 bg-gray-200 dark:bg-gray-800 rounded-full" />
              </div>
              <div className="relative pt-1">
                <div className="flex mb-2 items-center justify-between">
                  <div>
                    <span className="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-blue-600 bg-blue-200">
                      Task in progress
                    </span>
                  </div>
                  <div className="text-right">
                    <span className="text-xs font-semibold inline-block text-blue-600">
                      50%
                    </span>
                  </div>
                </div>
                <div className="overflow-hidden h-2 mb-4 text-xs flex rounded bg-gray-200">
                  <div style= {{width: "50%" }} className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-blue-500"></div>
                </div>
              </div>
              </div>
            </div>
          </div>
        <div className="flex flex-col space-y-4 md:space-y-6">
          <div className="rounded-lg border  border-gray-200  p-6 dark:bg-blue-900 dark:border-slate-800">
            <CurvedlineChart className="w-full aspect-[2/1]" />
          </div>
          <div className="grid gap-4 dark:bg-blue-900" />
          <div className="flex justify-end">
            <Button onClick={toggleOverlay} className="dark:text-white dark:hover:bg-blue-800" size="lg" variant="outline">
              <TextIcon className="h-6 w-6" />
            </Button>
          </div>
        </div>
        <section className="grid md:grid-cols-2 gap-4 items-start w-full max-w-7xl px-6 py-6 dark:bg-blue-900">
          <div className="space-y-6 dark:bg-blue-900">
            <div className="space-y-2">
              <h1 className="text-2xl font-bold dark:text-white">Personalized Recommendations</h1>
              <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
                Check out what we recommend for you
              </p>
            </div>
          </div>
        </section>
      </div>      
      {/* Chat Overlay */}
      {showOverlay && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center">
          <div className="bg-white p-6 rounded-lg shadow-lg w-96">
            <h2 className="text-lg font-bold mb-2">Chat with Us!</h2>
            <div className="overflow-auto h-64 mb-4">
              {messageHistory.map((msg, index) => (
                <div key={index} className={`p-2 ${msg.sender === 'ai' ? 'text-left' : 'text-right'}`}>
                  <span className="inline-block bg-gray-200 rounded p-2">{msg.message}</span>
                </div>
              ))}
            </div>
            <div className="flex">
              <input
                type="text"
                className="border p-2 w-full rounded-l"
                placeholder="Type your message..."
                value={currentMessage}
                onChange={(e) => setCurrentMessage(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && sendMessage()}
              />
              <button onClick={sendMessage} className="bg-blue-500 text-white p-2 rounded-r">
                Send
              </button>
            </div>
            <button onClick={toggleOverlay} className="mt-4 bg-red-500 text-white p-2 rounded">
              Close Chat
            </button>
          </div>
        </div>
      )}
    </>
  )
}


function CurvedlineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}


