/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3Zqger0jaET
 */
'use client'
import Button from "@/components/ui/button";

import React, { useState } from 'react';
import { ResponsiveLine } from "@nivo/line";
// import Notes from '../../app/NoteEditor/page'
import {redirect} from 'next/navigation'
import Link from "next/link";


export function Homepage() {
  const NoteEditor = () => {
    redirect('/NoteEditor')
  }

  return (
    <>
      <div className="grid md:grid-cols-2 gap-4 items-start w-full px-6 py-6 dark:bg-blue-900">
        <div className="grid md:grid-cols-2 gap-4 items-start w-full max-w-7xl px-6 py-6 dark:bg-blue-900">
          <div className="space-y-6 dark:bg-blue-900">
            <div className="space-y-2">
              <h1 className="text-2xl font-bold dark:text-white">Modules</h1>
              <p className="text-sm leading-none text-gray-500 dark:text-gray-400">Explore available modules</p>
            </div>
            <div className="space-y-4">
              <div className="flex flex-col items-center space-y-4">
                <div className="flex items-center space-x-4">
                  <img
                    alt="Image"
                    className="rounded-lg"
                    height="64"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "64/64",
                      objectFit: "cover",
                    }}
                    width="64"
                  />
                  <div className="space-y-1.5">
                    <h2 className="text-lg font-semibold dark:text-white">Introduction to Computer Science</h2>
                    <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
                      An introduction to the foundational concepts in computer science.
                    </p>
                  </div>
                </div>
                <div className="w-full h-4 bg-gray-200 dark:bg-gray-800 rounded-full" />
              </div>
              <div className="relative pt-1">
                <div className="flex mb-2 items-center justify-between">
                  <div>
                    <span className="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-blue-600 bg-blue-200">
                      Task in progress
                    </span>
                  </div>
                  <div className="text-right">
                    <span className="text-xs font-semibold inline-block text-blue-600">
                      50%
                    </span>
                  </div>
                </div>
                <div className="overflow-hidden h-2 mb-4 text-xs flex rounded bg-gray-200">
                  <div style= {{width: "50%" }} className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-blue-500"></div>
                </div>
              </div>
              </div>
            </div>
          </div>
        <div className="flex flex-col space-y-4 md:space-y-6">
          <div className="rounded-lg border  border-gray-200  p-6 dark:bg-blue-900 dark:border-slate-800">
            <CurvedlineChart className="w-full aspect-[2/1]" />
          </div>
          <div className="grid gap-4 dark:bg-blue-900" />
        </div>
        <section className="grid md:grid-cols-2 gap-4 items-start w-full max-w-7xl px-6 py-6 dark:bg-blue-900">
          <div className="space-y-6 dark:bg-blue-900">
            <div className="space-y-2">
              <h1 className="text-2xl font-bold dark:text-white">Personalized Recommendations</h1>
              <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
                Check out what we recommend for you
              </p>
            </div>
          </div>
        </section>
      </div>
    </>
  )
}
function CurvedlineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}


